---
title: js-有return的try catch finally执行顺序
date: 2021-02-03 15:41:37
categories:
- JavaScript
comments: true
---

## 结论


1. 不管有木有出现异常，finally 块中代码都会执行；
2. 当 try 和 catch 中有 return 时，finally 仍然会执行；
3. finally 是在 return 后面的表达式运算后执行的（此时并没有返回运算后的值，而是先把要返回的值保存起来，管 finally 中的代码怎么样，返回的值都不会改变，任然是之前保存的值），所以函数返回值是在 finally 执行前确定的；
4. finally 中最好不要包含 return，否则程序会提前退出，返回值不是 try 或 catch 中保存的返回值。

<!-- more -->



## 参考文章

[有return的情况下try catch finally的执行顺序（最有说服力的总结）](https://blog.csdn.net/kavensu/article/details/8067850)